[package]

# Note: Semantic Versioning is used: https://semver.org/
version = "0.1.0"

# Description
title = "Psi Lab Environments"
description = "Extension containing suite of environments for robot learning."
readme = "docs/README.md"
repository = "https://github.com/isaac-sim/IsaacLab"
category = "robotics"
keywords = ["robotics", "rl", "il", "learning"]

[dependencies]
"psilab" = {}
"isaaclab_tasks" = {}

[core]
reloadable = false

[[python.module]]
name = "psilab_tasks"
